### ISSUE TITLE
Invisiclues from Infocom games don't work

### ISSUE THREAD

**Issue by maudiagar** [curiousdannii/parchment#69] opened 2020-06-16 15:27 UTC
The screen gets frozen when using invisiclues from Infocom games.

For example with the Hitchhiker Guide of the Galaxy Gold Edition:

https://github.com/the-infocom-files/hitchhiker-invclues

Play this one and type "PISTAS" and then "PISTA", is a spanish version:

http://iplayif.com/?story=http%3A%2F%2Fmedia.textadventures.co.uk%2Fgames%2FzIQV2TDkgEiWpvtoPZFJJA%2Fhitchhiker3.z5

**Comment by curiousdannii** [comment] 2020-06-17 00:15
It works in [Lectrote](https://github.com/erkyrath/lectrote/releases), so the underlying virtual machine has fixed whatever bug this is. I do need to update Parchment, will try to get to it soon.

**Comment by cibersheep** [comment] 2020-06-17 00:41
> The screen gets frozen when using invisiclues from Infocom games.
That works with Firefox on Ubuntu 16.04

**Comment by maudiagar** [comment] 2020-06-17 04:38
Sorry, that was a temporary fix. Please type "hints" and then "hint"

**Comment by curiousdannii** [comment] 2020-06-17 04:43
Ah, I've found it. The game doesn't hang, but it does too many blank lines. If you scroll down, you can then enter a new keypress to use the menu. This is a duplicate of #48.

**Closed by curiousdannii** 2020-06-17 04:43 UTC

**Comment by maudiagar** [comment] 2020-06-17 04:44
Ah i see, so it is in my code?

**Comment by curiousdannii** [comment] 2020-06-17 04:47
No, it's a problem in the interpreter, which has been fixed upstream already, but I need to update Parchment.

**Comment by maudiagar** [comment] 2020-06-17 15:57
Thank you, in the meantime I solved it in my code changing the split to <SPLIT 3>
