### ISSUE TITLE
Allows margins larger than 25%

### ISSUE THREAD

**Issue by pbienst** [curiousdannii/parchment#147] opened 2024-05-10 09:27 UTC
When playing fullscreen, 25% margins is a bit too small to be comfortable on my monitor...

**Comment by curiousdannii** [comment] 2024-05-10 09:54
Duplicate of #36. Though it's not actually a percentage, it's got a max width.

**Closed by curiousdannii** 2024-05-10 09:54 UTC

**Comment by pbienst** [comment] 2024-05-10 10:56
Are you sure this is a duplicate? Full screen works fine, and I was just talking about the margins in the settings menu. They work, but the UI limits setting them to max 25% size. Can't you change the UI so that we can select values larger than 25% there?

**Comment by curiousdannii** [comment] 2024-05-10 11:03
There is no settings menu, I'm not sure what you're referring to?

**Comment by pbienst** [comment] 2024-05-10 11:17
Indeed, I submitted a bug report to the wrong project, sorry for wasting your time!
