### ISSUE TITLE
Very narrow windows cause "undefined" to be printed repeatedly

### ISSUE THREAD

**Issue by peardox** [curiousdannii/parchment#63] opened 2019-01-25 23:40 UTC
Go here

http://iplayif.com/?story=http%3A%2F%2Fwww.ifarchive.org%2Fif-archive%2Fgames%2Fzcode%2Fcurses.z5

This is Graham Nelson's Curses

Now make your browser as small as possible and refresh the page

I mentioned this to you about 10 years ago

This is of little concern to me today but important to you

Once upon a time I intended to release an app...

**Comment by curiousdannii** [comment] 2019-01-26 00:13
Can you explain a little more what the problem is? Can you provide a screenshot?

**Comment by peardox** [comment] 2019-01-26 01:50
Sure = gimme a moment to do some ScreenShots

I'll BRB a I find the value in your work

Following - Screenshots

**Comment by peardox** [comment] 2019-01-26 02:55
The white space was put there for a reason

I wanna do a web-based client using your superb code but when I hit < 32
this happens (this is from memory - 10 year ago)

I threw together a Cowther + Woods (worked) some 10 years ago to get him a
BlackBerry 10

When I say I thew it together I word it correctly (four project in 2 days)

I've never forgotten Parchment as a result

I'd love to bring text adventures to today's phone obsessed crowd

**Comment by curiousdannii** [comment] 2019-01-26 03:48
Please don't be silly, just explain what's going on. I can't see your screenshots. Were you trying to add them through replying to the email notification? I think you may need to add screenshots directly in the web page.

**Comment by peardox** [comment] 2019-01-26 12:40
Sorry if my last explanation was "Silly", that was not the intent

Here's how to replicate this yourself

Go to
http://iplayif.com/?story=http%3A%2F%2Fwww.ifarchive.org%2Fif-archive%2Fgames%2Fzcode%2Fcurses.z5

That works fine

Now resize your browser, width is the key here so make your browser an
narrow as possible (height is not a concern from my observations)

I'm using Chrome which limits me to now narrow I can go but this applies to
all browsers I've tried this on

Now you've got your super-thin browser load Curses again and you get
something like this

[image: curses2.png]

I hope this explains things better and isn't considered "Silly"

When something goes wrong I want to replicate it myself as I can't see the
issue myself otherwise

I did some work looking into this many years ago and it appeared to be the
Z5 stuff at the time if that helps

**Comment by peardox** [comment] 2019-01-26 12:50
Oh, forgot to mention

The white space stuff was as I don't know if my replies are public or
private

Hopefully the above message is a more straight forwards explanation

**Comment by curiousdannii** [comment] 2019-01-26 13:51
None of your screenshots are displaying. Please go to the github website and post the screenshot directly.

**Comment by peardox** [comment] 2019-01-26 13:59
Dannii

If you simply follow the text you can see it without screenshots

Can I simply ask what platform + browser you're using so I can compare
results

I'll upload the image to my server - back in a mo

Don't forget the platform + browser stuff - it's important

**Comment by peardox** [comment] 2019-01-26 14:39
Oops

wrong URLs

I mean these specific URLs

https://ifdb.tads.org/

and

http://iplayif.com/

The latter is the baddie - hope that's not you

Basically Google will de-list you next year

I'll take you a proper deploy and do a HTTPS on it - this will take me a
while

**Comment by peardox** [comment] 2019-01-26 16:42
Told you this would take a while

https://if.peardox.com/

This is a GIT clone of Parchment and you'll notice it's secure

So - whoever owns http://iplayif.com/ needs to do the same to their site

If I leave my site up (I won't), this one is a special for you only to
explain things

About 2010 I downloaded all the IF on IFDB

I can easily add every add all those to if.peardox.com (done it before -
easy to do again) rather than redirect to DB

Gonna have to mail myself so you get a chance to see if.peardox.com (I'm
actually interested in how it scales with such a crappy name)

Can we be friends now?

IF is low priority for me - I visit it very occasionally, sadly yesterday
was my IF day...

I can help you if you desire, it should take less than a day for me to
(maybe two) to sort things out

Should you desire my aid all you have to do us ask

I'm Simon Booth, my email is simon@peardox.com, I live in Manchester, UK. I
have MANY friends who can do translation services - I simply need the
English and Target language(s) - please bear in mind that I have to develop
the tools to repack a Z5

**Comment by peardox** [comment] 2019-01-30 23:50
It wan't 10 years ago, more like 7 I guess - I know I first used Parchment in 2010

I noticed it at this point and did report it

The cool thing about letsencrypt is that it automates the redirect and you don't have to pay for a SSL cert - assuming you're using Apache, it's easy - other servers are more complicates). LetsEnctypt is well supported but you have to renew every 90 days (a trade off for a min's work)

i.e. you can HTTPS http://iplayif.com with a forced redirect very quickly (try it on a test server first!)

Googling you demotes ifplay since - err - bad memory, 2017 I think? Thinks get worse soon as well with Chrome I understand (Google suck)

**Comment by curiousdannii** [comment] 2021-11-24 02:17
I think this is fixed now

**Closed by curiousdannii** 2021-11-24 02:17 UTC
Labels: bug
